[package]
name = "owlcat-blueprint-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde_json = "1.0.148"
serde_json_path = "0.7.2"
walkdir = "2.5.0"
